import os

NEBIUS_API_KEY = os.getenv("NEBIUS_API_KEY")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

DEFAULT_SILENCE_TIMEOUT = 0.5